site_name: Zoom @ HackCville
theme:
  name: material
  logo: HC.png

docs_dir: "content"
extra:
  social: 
     - icon: fontawesome/brands/twitter
       link: https://twitter.com/hackcville
     - icon: fontawesome/brands/linkedin
       link: https://www.linkedin.com/company/hackcville/
     - icon: fontawesome/solid/globe
       link: https://hackcville.com/

extra_css:
  - stylesheets/extra.css



markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
plugins:
    - redirects:
        redirect_maps:
            'nodelite/': 'https://forms.gle/VpoYE9WaUfAdZqhT8'
            'nodepro': 'https://nodepro.hackcville.com/zoom'
nav:
    - Home: 'index.markdown'





