site_name: Node Pro
theme:
  name: material
  logo: HC.png
  

docs_dir: "content"
extra:
  social: 
     - icon: fontawesome/brands/twitter
       link: https://twitter.com/christianfjung
     - icon: fontawesome/brands/linkedin
       link: http://linkedin.christianfjung.com/
     - icon: fontawesome/solid/globe
       link: http://christianfjung.com/
     - icon: fontawesome/brands/github
       link: http://github.christianfjung.com/
extra_css:
  - stylesheets/extra.css
# nav:
#     - Home: 'index.md'
#     - "Week 1":
#     - "Week 2":
#         - 'Overview': 'week2/readme.md'

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
plugins:
    - redirects:
        redirect_maps:
            'signin/': 'https://forms.gle/VpoYE9WaUfAdZqhT8'
            'zoom': 'https://virginia.zoom.us/j/97419672198?pwd=TDViNXFEWm9kODhvM1g5TkZ4aDdRUT09'
            'api': "http://nodepro.hackcville.com/week2/data/csvjson.json"
            'eval': 'https://forms.gle/2qKL31GHKDk7bePf6'
            'feedback' : 'https://forms.gle/MBcqWSbYJ2gEBVwy6'
            'template': 'https://docs.google.com/document/d/1Y7_TNWo3zKHnic32-_Oy1ZNHCrm-RmUwYXuy2d9kvSA/edit?usp=sharing'

nav:
    - Home: 'index.markdown'
    - "Week 1":
        - Workshop 1: "week1/README.md"
        - HW 1: "week1/hw1.md"
    - "Week 2":
        - Workshop 2: "week2/README.md"
        - HW 2: "week2/hw2.md"
        - Lab 2: "week2/lab2.md"
    - "Week 3":
        - Workshop 3: "week3/README.md"
        - HW 3A Pre-lab: "week3/hw3.md"
        - Lab 3: "week3/lab3/README.md"
        - HW 3B : "week3/hw3b.md"

    - "Week 4":
        - "Workshop 4": "week4/README.md"
        - "Lab 4": "week4/lab4.md"
    - "Week 5":
        - "Workshop 5": "week5/README.md"
        - "Lab 5": "week5/lab5.md"
    - "Week 6":
        - "Workshop 6": "week6/README.md"
    - "Week 7":
        - "Workshop 7": "week7/README.md"
    - "Week 8":
        - "Workshop 8": "week8/README.md"
    - "Week 9":
        - "Workshop 9": "week9/README.md"

    - "Projects":
        - Project 1: "project1/README.md"
        - Final Project: "project3/README.md"




